demo_01/demo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^register/$',views.register,name='register'),
    url(r'^show_index/$',views.show_index,name='show_index'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^(?P<u_id>\d+)/update/$', views.update, name="update"),
    url(r'^(?P<u_id>\d+)/change_password/$', views.change_password, name="change_password"),
    url(r'^(?P<u_id>\d+)/delete_user/$', views.delete_user, name="delete_user"),

    #文章的增删改查
    url(r"^add_article/$",views.add_article,name='add_article'),
    url(r"^(?P<a_id>\d+)/show_article/$",views.show_article,name='show_article'),
    url(r"self_article/$",views.self_article,name='self_article'),
    url(r"^(?P<a_id>\d+)/update_article/$",views.update_article,name='update_article'),
    url(r"^(?P<a_id>\d+)/delete_article/$",views.delete_article,name='delete_article'),

    #验证码
    url(r'^code/$',views.code,name='code'),

    url(r'^(?P<username>\w+)/check_username/$',views.check_username, name='check_username'),
]

demo_01/demo_01/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^demo/',include('demo.urls',namespace='demo')),
    url(r'^ueditor/', include('DjangoUeditor.urls')),

]

demo_01/demo/models.py
from datetime import datetime

from django.db import models

from DjangoUeditor.models import UEditorField
# Create your models here.

class User(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique=True, verbose_name="用户名称")
    password = models.CharField(max_length=50, verbose_name="用户密码")
    age = models.IntegerField(default=18, verbose_name="用户年龄")
    nickname = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, verbose_name="用户邮箱")
    gender = models.BooleanField(default=0)  # 默认是0 表示男生，1表示女生
    header = models.ImageField(upload_to="static/demo/image/headers/",default="static/demo/image/headers/9.jpg",verbose_name="用户头像")

class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255,verbose_name="文章标题")
    # content = models.TextField(verbose_name="文章内容")
    content = UEditorField()
    publishtime = models.DateTimeField(auto_now_add=True)
    modifyTime = models.DateTimeField(auto_now=True)

    #外键
    author = models.ForeignKey(User,on_delete=models.CASCADE)

demo_01/demo/views.py
from io import BytesIO
import uuid

from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse

#判断是否为字典，如果是将抓拿华为JSON字符串
from django.http import JsonResponse

from django.forms.models import model_to_dict

from django.core.serializers import serialize
# Create your views here.
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST,require_http_methods
#引用django内置的分页模板
from django.core.paginator import Paginator

from . import utils
from . import models
from . import redis_utils
from .utils import require_login
from django.conf import settings

import logging

@require_login
def index(request):
    logger = logging.getLogger("django")
    logger.warning("首页开始运行了……")

    articles = redis_utils.get_all_articles(ischange=True)

    page_size = int(request.GET.get("page_size",settings.PAGE_SIZE))
    page_now = int(request.GET.get("page_now",1))
    paginator = Paginator(articles,page_size)
    page = paginator.page(page_now)

    return render(request,"demo/index.html",{"page":page,"page_size":page_size})


def login(request):
    if request.method == "GET":
        return render(request, "demo/login.html")
    elif request.method == "POST":
        username = request.POST["username"]
        passwords = request.POST["password"]
        password = utils.hmac_by_md5(passwords)
        # code = request.POST["code"]
        #
        # mycode = request.session["code"]
        # if code.upper() != mycode.upper():
        #     return render(request, "demo/login.html", {"msg": "验证码输入错误！"})
        # del mycode

        try:
            user = models.User.objects.get(username = username,password = password)
            #会话跟踪
            request.session["loginUser"] = user
            response = redirect(reverse("demo:index"))
            #使用cookie记录用户名称,cookie不能存储中文
            try:
                check_box = request.POST["check_box"]
                if check_box:
                    response.set_cookie("username",user.username,max_age=3600 * 24 * 14)
                    return response
            except:
                return response
        except:
            return render(request,"demo/login.html",{"msg":"登录失败，请重新登录！！"})

def register(request):
    if request.method == "GET":
        return render(request,"demo/register.html")
    elif request.method == "POST":
        try:
            username = request.POST["username"].strip()
            email = request.POST["email"].strip()
            password = request.POST["password"].strip()
            c_password = request.POST["c_password"].strip()

            if len(username) < 1:
                return render(request ,"demo/register.html", {"msg":"用户名称不能为空！！"})
            if len(password) < 6:
                return render(request, "demo/register.html", {"msg": "用户密码不能小于六位！！"})
            if password != c_password:
                return render(request, "demo/register.html", {"msg": "两次密码输入不一致！！"})
            if len(email) < 0:
                return render(request, "demo/register.html", {"msg": "邮箱不能为空！！"})
            try:
                user = models.User.objects.get(username = username)
                return render(request, "demo/register.html", {"msg": "账号已存在，请重新输入！！"})
            except:
                password = utils.hmac_by_md5(password)
                user = models.User(username = username,password = password,email = email)
                user.save()
                return render(request, "demo/login.html", {"msg": "账号注册成功,请登录！！"})
        except Exception as e:
            print(e)
            return render(request, "demo/register.html", {"msg": "账号不能为空"})

def show_index(request):
    return render(request, "demo/show_index.html")

@require_login
def update(request,u_id):
    user = models.User.objects.get(id=u_id)
    if request.method == "GET":
        return render(request,"demo/update.html", {"user":user})
    elif request.method == "POST":
        nickname = request.POST["nickname"]
        email = request.POST["email"]
        age = request.POST["age"]
        avatar = request.FILES.get("avatar",user.header)
        print(avatar)

        user.nickname = nickname
        user.email = email
        user.age = age
        user.header =  avatar
        request.session["loginUser"] = user
        user.save()
        return redirect(reverse("demo:index"))

#修改密码
def change_password(request, u_id):
    user = models.User.objects.get(pk=u_id)
    if request.method == "GET":
        return render(request,"demo/update.html", {"user":user})
    elif request.method == "POST":
        pwd = request.POST["pwd"]
        n_pwd = request.POST["n_pwd"]
        c_pwd = request.POST["c_pwd"]
        print(pwd,n_pwd,c_pwd)
        if len(n_pwd) < 6:
            # return render(request, "demo/update.html", {"user": user, "msg": "密码不能小于六位!"})
            return JsonResponse({"msg": "密码不能小于六位!","success":True})

        if utils.hmac_by_md5(pwd) == user.password:
            if n_pwd == c_pwd:
                user.password = utils.hmac_by_md5(n_pwd)
                user.save()
                # return  render(request,"demo/login.html")
                return JsonResponse({"msg": "密码修改成功", "success": False})
            else:
                # return render(request,"demo/update.html", {"user":user,"msg":"两次密码输入不一致!"})
                # return redirect(reverse("demo:change_password", kwargs={"user":user,"msg":"两次密码输入不一致!"}))
                return JsonResponse({"msg": "两次密码输入不一致!", "success": True})
        else:
            # return render(request, "demo/update.html", {"user": user, "msg": "原密码输入错误！"})
            # return redirect(reverse("demo:change_password", kwargs={"user": user, "msg": "密码输入错误！"}))
            return JsonResponse({"msg": "原密码输入错误！", "success": True})


def delete_user(request,u_id):
    user = models.User.objects.get(pk=u_id)
    user.delete()
    return redirect("/demo/show_index/")


def logout(request):
    try:
        del request.session["loginUser"]

    finally:
        return redirect(reverse("demo:show_index"))


@require_login
def add_article(request):
    if request.method == "GET":
        return render(request, "demo/add_article.html")
    elif request.method == "POST":
        title = request.POST["title"]
        content1 = request.POST["content"]
        author = request.session["loginUser"]

        content = utils.clear_html_re(content1)
        article = models.Article(title=title, content=content,author=author)
        article.save()
        #把数据添加到缓存中
        redis_utils.get_self_article(author=author, ischange=True)
        redis_utils.get_all_articles()

        return JsonResponse({"msg": "文章添加成功", "success": True})
        # return redirect(reverse("demo:show_article", kwargs={"a_id": article.id}))

@require_login
def show_article(request,a_id):

    at = models.Article.objects.get(pk=a_id)
    return render(request,"demo/show_article.html",{"article":at})


@require_login
def self_article(request):
    articles = redis_utils.get_self_article(author=request.session["loginUser"])
    return render(request,"demo/self_article.html",{"articles":articles})


@require_login
def update_article(request,a_id):
    at = models.Article.objects.get(pk=a_id)
    if request.method == "GET":
        return render(request, "demo/update_article.html", {"at": at})
    else:
        title = request.POST["title"]
        content = request.POST["content"]
        at.content = content
        at.title = title
        at.save()
        return redirect(reverse("demo:self_article"))

def delete_article(request, a_id):
    at = models.Article.objects.get(pk=a_id)
    author = request.session["loginUser"]
    at.delete()
    redis_utils.get_self_article(author=author, ischange=True)
    return redirect(reverse("demo:self_article"))


def code(request):
    img, code = utils.create_code()
    #将数据保存到session
    request.session["code"] = code

    file = BytesIO()
    img.save(file,'PNG')

    return HttpResponse(file.getvalue(), "image/png")


# @require_http_methods("GET","POST")
# @require_POST
# # @csrf_exempt
# def ajax_hello(request):
#     id = request.POST["id"]
#     name = request.POST["name"]
#     print(id,name)
#     #model_to_dict(at)先将对象转化为字典对象，然后转化为JSON对象
#     #at = models.Article.objects.get(pk=id)
#     # return JsonResponse(model_to_dict(at))
#     ats = models.Article.objects.all()
#     return HttpResponse(serialize("json",ats))

def check_username(request,username):
    qs = models.User.objects.filter(username=username)
    if len(qs):
        return JsonResponse({"msg":"该用户名已存在，请从新输入！！","success":False})
    else:
        return JsonResponse({"msg":"恭喜您，用户名可用！！","success":True})

demo_01/demo/templates/demo/add_article.html
{% extends 'base.html' %}

{% block title %}
写文章
{% endblock %}

{% block self_css %}
<link rel="stylesheet" href="/static/ueditor/themes/default/css/ueditor.css">
<script type="text/javascript" src="/static/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/static/ueditor/ueditor.all.min.js"></script>
<script type="text/javascript" src="/static/ueditor/lang/zh-cn/zh-cn.js"></script>
{% endblock %}

{% block lb_picture %}
<div class="panel panel-primary">
      <div class="panel-heading">
          <h5>发表文章</h5>
      </div>

      <div class="panel-body">
        <div style="color: red;" id="msg">{{msg}}</div>
        <!--<form class="form-horizontal" action="/demo/add_article/" method="post">-->
            {% csrf_token %}
          <div class="form-group">
            <div class="col-md-10 col-md-offset-1">
              <input type="text" class="form-control" name="title" id="title" placeholder="请输入文章的标题">
            </div>
          </div>
          <div class="form-group">
            <div class="row">
                <textarea class="col-md-10 col-md-offset-1" id="id_content" name="content"></textarea>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-danger" onclick="add_article()">发表文章</button>
            </div>
          </div>
        </form>


      </div>
    </div>
{% endblock %}
{% block bloger_info %}
{%  endblock %}
{% block show_article %}
<script>
     var id_content = UE.getEditor('id_content',{
     'initialFrameWidth': 1000,
     'initialFrameHeight': 600,
     'serverUrl': '/ueditor/controller/?imagePathFormat=&filePathFormat='
     });
      id_content.ready(function(){
      });


     function add_article() {
         title = $("#title").val();
         content = id_content.getContent();

         $.ajax({
             url: "/demo/add_article/",
             method: "POST",
             data: {"title": title, "content": content, "csrfmiddlewaretoken": "{{ csrf_token }}"},
             dataType: "json",
             success: function (data) {
                 if (data.success) {
                     $("#msg").html(data.msg);
                     $("#title").val("");
                     id_content.setContent("")

                     //演示前端跳转页面
                     // window.location.pathname = "/blog/index/"

                 } else {
                     $("#msg").html("文章添加失败，请重新添加！！！")
                 }
             }

         })


     }
     
</script>
{% endblock %}

demo_01/demo/templates/demo/index.html
{% extends 'base.html' %}

demo_01/demo/templates/demo/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.min.js"></script>
    <script src="/static/js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <!--引用自己的样式-->
    <link rel="stylesheet" href="/static/demo/css/login.css">
</head>
<body>
<div class="container">
    <!-- Nav tabs -->
    <p id="logo">简书</p>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login">
                <ul class="nav nav-pills" role="tablist">
                    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">登录</a></li>
                    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">注册</a></li>
                </ul>

                <!--Tab panes-->
                <div class="tab-content">
                    <span>{{msg}}</span>
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <form class="form-horizontal" action="/demo/login/" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2  control-label">账号</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="username" id="inputEmail3" placeholder="Admin">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
                                <div class="col-sm-10">
                                    <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword5" class="col-sm-2 control-label">验证码</label>
                                <div class="col-sm-4">
                                    <input type="text" name="code" class="form-control" id="inputPassword5" placeholder="验证码">
                                </div>
                                <div class="col-sm-4">
                                    <a href="#" onclick="changeCode()"><img id="code" src="{% url 'demo:code' %}" title="点击刷新"></a>
                                </div>

                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="check_box"> 记住密码
                                        </label>
                                        <span id="problem">登录遇到问题?</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-default" id="button1">登录</button>
                                </div>
                            </div>
                            <p class="text-center"><br/>社交帐号登录</p>
                            <ul class="nav nav-pills col-md-offset-3 tubiao">
                                <li role="presentation"><a href="#"><img src="/static/demo/image/headers/QQ.png" class=""></a></li>
                                <li role="presentation"><a href="#"><img src="/static/demo/image/headers/weixin.png"></a></li>
                                <li role="presentation"><a href="#"><img src="/static/demo/image/headers/weibo.png"></a></li>
                                <li role="presentation"><a href="#">其它</a></li>
                            </ul>
                        </form>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">
                        <form class="form-horizontal">
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">账号</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" placeholder="Admin">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">手机</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" placeholder="Phone">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-default">注册</button>
                                </div>
                            </div>
                            <p class="text-center">点击 “注册” 即表示您同意并愿意遵守简书<br/>
                                <span class="text-primary">用户协议</span> 和 <span class="text-primary">隐私政策</span> 。</p>
                            <!--<p class="text-center">社交帐号登录</p>-->
                            <ul class="nav nav-pills col-md-offset-2 tubiao">
                                <li role="presentation"><a href="#">其它登录</a></li>
                                <li role="presentation"><a href="#"><img src="/static/demo/image/headers/QQ.png" class=""></a></li>
                                <li role="presentation"><a href="#"><img src="/static/demo/image/headers/weixin.png"></a></li>
                                <li role="presentation"><a href="#"><img src="/static/demo/image/headers/weibo.png"></a></li>
                            </ul>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    <script>
        function changeCode() {
//            document.getElementById("code").src = "/demo/code?id="+ new Date().getTime()
            document.getElementById("code").src = "/demo/code?id="+ Math.random()
        }
    </script>
</body>
</html>

demo_01/demo/templates/demo/self_article.html
{% extends 'base.html' %}

{% block title %}
查看自己发表的文章
{% endblock %}

{% block lb_picture %}
{% endblock %}
{% block show_article %}
<!-- 主要展示列，展示各项文章信息等 -->
<div class="col-md-8">
    <!--<div class="page-header">-->
    <!--<h3>热门文章 <small>这里能找到技术前沿的各位大神的文章内容</small></h3>-->
    <!--</div>-->
    <div class="row author-article">
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="home">
                {% for at in articles %}
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading"><a href="{% url 'demo:show_article' at.id %}">{{at.title}}</a></h4>
                        {{at.content | safe}}
                    </div>
                    <div class="media-left media-middle">
                        <a href="#">
                            <img class="media-object " src="/static/demo/image/articles/1.jpg" alt="图片">
                        </a>
                    </div>
                    <div class="media-bottom text-muted">
                        <span class="glyphicon glyphicon-eye-open">169</span>
                        <span class="glyphicon glyphicon-comment">18</span>
                        <span class="glyphicon glyphicon-heart">200</span>
                        <span>&nbsp;{{at.publishtime}}</span>
                        <a href="{% url 'demo:update_article' at.id %}">修改文章</a>
                        <a onclick="return window.confirm('您确定要删除这篇文章吗？')" href="{% url 'demo:delete_article' at.id %}">删除文章</a>

                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!--<a href="{% url 'demo:update_article' at.id %}">修改</a>-->
<!--<a onclick="return window.confirm('您确定要删除这篇文章吗？')" href="{% url 'demo:delete_article' at.id %}">删除</a>-->

demo_01/demo/templates/demo/show_article.html
{% extends 'base.html' %}

{% block title %}
写文章
{% endblock %}

{% block lb_picture %}

<div class="panel-heading">文章详情</div>
      <div class="panel-body">
         <div class="row">
            <div class="panel panel-default">
              <div class="panel-heading">
                  <h4 class="text-center">
                      {{article.title | truncatechars:50}}
                  </h4>
                  <div class="text-right">
                          作者：{{article.author.nickname}}|
                          发表时间：{{article.publishTime}}|
                          修改时间：{{article.modifyTime}}
                  </div>
              </div>
              <div class="panel-body">
                {{article.content | safe}}
              </div>
            </div>
          </div>
      </div>
    </div>
{% endblock %}
{% block bloger_info %}
{%  endblock %}
{% block show_article %}
{% endblock %}

demo_01/demo/templates/demo/show_index.html
{% extends 'base.html' %}

{% block title %}
主页
{% endblock %}

{% block login %}

<li><a href="{% url 'demo:login' %}">登录</a></li>
<li><a href="{% url 'demo:register' %}">注册</a></li>
{% endblock %}
{% block bloger_info %}
<!--<button onclick="sendajax()">发送ajax</button>-->

<script>
    // function sendajax() {
    //     var xhr = new XMLHttpRequest();
    //     // 2.打开连接
    //     xhr.open("POST","/demo/ajax_hello/?id=3&name=hwc",true);
    //     xhr.onreadystatechange = function () {
    //         //接收服务器返回的参数
    //         if (xhr.readyState == 4 && xhr.status == 200){
    //             console.log(xhr.responseText)
    //         }
    //     };
    //     //4.发送请求
    //     xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
    //     xhr.send("id=3&name=hwc");
    //
    // }
    // function sendajax(options) {
    //     var xhr = new XMLHttpRequest();
    //     xhr.open(options.method,options.url,options.async);
    //     xhr.onreadystatechang = options.success;
    //     xhr.send();
    // }
    //
    // sendajax({
    //     method:"GET",
    //     url:"demo/ajax_hello",
    //     async:true,
    //     success:function () {
    //
    //     }
    // })
    // function sendajax() {
    //     $.ajax({
    //         url:"/demo/ajax_hello/",
    //         method:"POST",
    //         data:{"id":1,"name":"hwc","csrfmiddlewaretoken":"{{ csrf_token }}"},
    //         dataType:"json",
    //         success:function (data) {
    //             console.log(data)
    //         },
    //         error:function () {
    //
    //         },
    //     })
    // }
</script>

{% endblock %}

demo_01/demo/templates/demo/update_article.html
{% extends 'base.html' %}

{% block title %}
写文章
{% endblock %}

{% block lb_picture %}

{% endblock %}
{% block bloger_info %}
<div class="panel panel-primary">
      <div class="panel-heading">
          <h5>发表文章</h5>
      </div>

      <div class="panel-body">
        <div style="color: red;">{{msg}}</div>
        <form class="form-horizontal" action="/demo/{{at.id}}/update_article/" method="post">
            {% csrf_token %}
          <div class="form-group">
            <div class="col-md-10 col-md-offset-1">
              <input type="text" class="form-control" name="title" id="title" value="{{at.title}}">
            </div>
          </div>
          <div class="form-group">
            <div class="row">
                <textarea class="col-md-10 col-md-offset-1" name="content" id="content" cols="30" rows="20">{{at.content}}</textarea>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-danger">确认修改</button>
            </div>
          </div>
        </form>


      </div>
    </div>
{%  endblock %}
{% block show_article %}
{% endblock %}